### ISSUE TITLE
Move away `TODO` error message

### ISSUE THREAD

**Issue by cirocosta** [wedeploy/letsencrypt#16]
Hey,

it looks like there's a TODO error message leaking from a dependency:

```
le.challenges[http-01].loopback should be defined as function (opts, domain, token, cb) { ... } and should prove (by external means) that the ACME server challenge 'http-01' will succeed
TODO: modules which depend on this module should expose this error properly but since some of them don't, I expose it here directly:
Error: [Error] letiny-core: not 200 ok
    at bodyToError (/wedeploy-container/node_modules/le-acme-core/lib/get-certificate.js:55:15)
    at /wedeploy-container/node_modules/le-acme-core/lib/get-certificate.js:99:20
    at Request._callback (/wedeploy-container/node_modules/le-acme-core/lib/acme-client.js:113:7)
    at Request.self.callback (/wedeploy-container/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/wedeploy-container/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/wedeploy-container/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
{ type: 'urn:acme:error:rateLimited',
  detail: 'Error creating new authz :: Too many invalid authorizations recently.',
  status: 429 }
> ERR! Error: [Error] letiny-core: not 200 ok
> ERR!     at bodyToError (/wedeploy-container/node_modules/le-acme-core/lib/get-certificate.js:55:15)
> ERR!     at /wedeploy-container/node_modules/le-acme-core/lib/get-certificate.js:99:20
> ERR!     at Request._callback (/wedeploy-container/node_modules/le-acme-core/lib/acme-client.js:113:7)
```

**Comment by ipeychev** [comment]
Umm, this is coming from a dependency indeed. What you mean with "Move it away"? We don't control it. Or you mean to fork it, suppress the message and use the fork in our project?

**Comment by eduardolundgren** [comment]
I think he meant `try/catch` it and handle differently.

**Comment by ipeychev** [comment]
Yeah, that would be an easy solution, but there is always a "but..." :)

The problem is that this `TODO` is not part of the error. It is some `console.error` they print directly. [Here](https://github.com/Daplie/le-acme-core/blob/984bbf69a8fa5f479f8703c042c45ed21b65f16c/lib/get-certificate.js#L60) is the code. That's why I was wondering how exactly to suppress it. We can't suppress it (in a good way) unless we fork their code, can we?
